/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.gcto.dataVDM;

/**
 *
 * @author camilo
 */
public class AbrirProyectoNuevo extends javax.swing.JDialog
{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AbrirProyectoNuevo.class.getName());

    /**
     * Creates new form AbrirProyectoNuevo
     */
    public AbrirProyectoNuevo(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnGrp = new javax.swing.ButtonGroup();
        lblTit = new javax.swing.JLabel();
        tabbPnl = new javax.swing.JTabbedPane();
        pnlCrearProy = new javax.swing.JPanel();
        lblTitCSV = new javax.swing.JLabel();
        flieChoosserCSV = new javax.swing.JFileChooser();
        pnlProy = new javax.swing.JPanel();
        pnlDatos = new javax.swing.JPanel();
        lbl3ph4w = new javax.swing.JLabel();
        rb3ph4w = new javax.swing.JRadioButton();
        lbl3ph3w = new javax.swing.JLabel();
        rb3ph3w = new javax.swing.JRadioButton();
        lbl1ph2wln = new javax.swing.JLabel();
        rb1ph2wLN = new javax.swing.JRadioButton();
        lbl1ph2wll = new javax.swing.JLabel();
        rb1ph2wLL = new javax.swing.JRadioButton();
        lbl1ph3wlln = new javax.swing.JLabel();
        rb1ph3wLLN = new javax.swing.JRadioButton();
        rb3ph3wLLN = new javax.swing.JRadioButton();
        lbl3ph3wlln = new javax.swing.JLabel();
        lbl3ph3wlN = new javax.swing.JLabel();
        rb3ph2wLN = new javax.swing.JRadioButton();
        pnlDatosProy = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblUbica = new javax.swing.JLabel();
        txtUbica = new javax.swing.JTextField();
        lblTec = new javax.swing.JLabel();
        txtTec = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblTab = new javax.swing.JLabel();
        txtTab = new javax.swing.JTextField();
        lblTitRuta = new javax.swing.JLabel();
        txtRutaCSV = new javax.swing.JTextField();
        pnlDatoME435 = new javax.swing.JPanel();
        lblBobina = new javax.swing.JLabel();
        cmbRelBob = new javax.swing.JComboBox<>();
        lblRelTension = new javax.swing.JLabel();
        txtRelPrim = new javax.swing.JTextField();
        lblA = new javax.swing.JLabel();
        txtRelPrim1 = new javax.swing.JTextField();
        lblPeriod = new javax.swing.JLabel();
        spnPeriod = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        pnlAbrirProy = new javax.swing.JPanel();
        lblTitVMD = new javax.swing.JLabel();
        fileCooserVMD = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTit.setBackground(new java.awt.Color(204, 255, 255));
        lblTit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/gcto/dataVDM/abirCSV.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lblTit, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.lblTit.text")); // NOI18N
        lblTit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblTit.setOpaque(true);

        tabbPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabbPnl.setName("Abrir"); // NOI18N

        lblTitCSV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lblTitCSV, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.lblTitCSV.text")); // NOI18N

        pnlProy.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.pnlProy.border.title"))); // NOI18N
        pnlProy.setToolTipText(org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.datosProy.toolTipText")); // NOI18N
        pnlProy.setName("datosProy"); // NOI18N

        pnlDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.pnlDatos.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION)); // NOI18N

        lbl3ph4w.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl3ph4w.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/gcto/dataVDM/3PH4W.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lbl3ph4w, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.lbl3ph4w.text")); // NOI18N
        lbl3ph4w.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl3ph4w.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnGrp.add(rb3ph4w);
        rb3ph4w.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(rb3ph4w, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.rb3ph4w.text")); // NOI18N
        rb3ph4w.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb3ph4w.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rb3ph4wActionPerformed(evt);
            }
        });

        lbl3ph3w.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl3ph3w.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/gcto/dataVDM/3PH3W.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lbl3ph3w, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.lbl3ph3w.text")); // NOI18N
        lbl3ph3w.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl3ph3w.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnGrp.add(rb3ph3w);
        rb3ph3w.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(rb3ph3w, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.rb3ph3w.text")); // NOI18N
        rb3ph3w.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rb3ph3wActionPerformed(evt);
            }
        });

        lbl1ph2wln.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl1ph2wln.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/gcto/dataVDM/1PH2W-NL.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lbl1ph2wln, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.lbl1ph2wln.text")); // NOI18N
        lbl1ph2wln.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl1ph2wln.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnGrp.add(rb1ph2wLN);
        org.openide.awt.Mnemonics.setLocalizedText(rb1ph2wLN, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.rb1ph2wLN.text")); // NOI18N

        lbl1ph2wll.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl1ph2wll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/gcto/dataVDM/1PH2W-LL.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lbl1ph2wll, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.lbl1ph2wll.text")); // NOI18N
        lbl1ph2wll.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl1ph2wll.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnGrp.add(rb1ph2wLL);
        org.openide.awt.Mnemonics.setLocalizedText(rb1ph2wLL, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.rb1ph2wLL.text")); // NOI18N
        rb1ph2wLL.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rb1ph2wLLActionPerformed(evt);
            }
        });

        lbl1ph3wlln.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl1ph3wlln.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/gcto/dataVDM/1PH2W-LL.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lbl1ph3wlln, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.lbl1ph3wlln.text")); // NOI18N
        lbl1ph3wlln.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl1ph3wlln.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnGrp.add(rb1ph3wLLN);
        org.openide.awt.Mnemonics.setLocalizedText(rb1ph3wLLN, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.rb1ph3wLLN.text")); // NOI18N

        btnGrp.add(rb3ph3wLLN);
        rb3ph3wLLN.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(rb3ph3wLLN, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.rb3ph3wLLN.text")); // NOI18N
        rb3ph3wLLN.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rb3ph3wLLNActionPerformed(evt);
            }
        });

        lbl3ph3wlln.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl3ph3wlln.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/gcto/dataVDM/3PH3W_FFN.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lbl3ph3wlln, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.lbl3ph3wlln.text")); // NOI18N
        lbl3ph3wlln.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl3ph3wlln.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lbl3ph3wlN.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl3ph3wlN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/gcto/dataVDM/3PH2W_FN.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lbl3ph3wlN, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.lbl3ph3wlN.text")); // NOI18N
        lbl3ph3wlN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl3ph3wlN.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnGrp.add(rb3ph2wLN);
        rb3ph2wLN.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(rb3ph2wLN, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.rb3ph2wLN.text")); // NOI18N
        rb3ph2wLN.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rb3ph2wLNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl3ph4w)
                        .addGap(18, 18, 18)
                        .addComponent(lbl3ph3w)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl3ph3wlln)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl3ph3wlN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl1ph2wln)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl1ph2wll))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(rb3ph4w)
                        .addGap(48, 48, 48)
                        .addComponent(rb3ph3w)
                        .addGap(47, 47, 47)
                        .addComponent(rb3ph3wLLN)
                        .addGap(43, 43, 43)
                        .addComponent(rb3ph2wLN)
                        .addGap(41, 41, 41)
                        .addComponent(rb1ph2wLN)
                        .addGap(42, 42, 42)
                        .addComponent(rb1ph3wLLN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(rb1ph2wLL))
                    .addComponent(lbl1ph3wlln))
                .addGap(85, 85, 85))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl3ph3w)
                    .addComponent(lbl3ph3wlln)
                    .addComponent(lbl3ph4w)
                    .addComponent(lbl3ph3wlN)
                    .addComponent(lbl1ph2wln)
                    .addComponent(lbl1ph2wll)
                    .addComponent(lbl1ph3wlln))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb3ph4w)
                    .addComponent(rb3ph3w)
                    .addComponent(rb3ph3wLLN)
                    .addComponent(rb3ph2wLN)
                    .addComponent(rb1ph2wLN)
                    .addComponent(rb1ph3wLLN)
                    .addComponent(rb1ph2wLL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDatosProy.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.pnlDatosProy.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION)); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblName, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.lblName.text")); // NOI18N

        txtName.setText(org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.txtName.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblUbica, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.lblUbica.text")); // NOI18N

        txtUbica.setText(org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.txtUbica.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblTec, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.lblTec.text")); // NOI18N

        txtTec.setText(org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.txtTec.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblCity, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.lblCity.text")); // NOI18N

        txtCity.setText(org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.txtCity.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblTab, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.lblTab.text")); // NOI18N

        txtTab.setText(org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.txtTab.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblTitRuta, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.lblTitRuta.text")); // NOI18N

        txtRutaCSV.setText(org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.txtRutaCSV.text")); // NOI18N
        txtRutaCSV.setEnabled(false);

        javax.swing.GroupLayout pnlDatosProyLayout = new javax.swing.GroupLayout(pnlDatosProy);
        pnlDatosProy.setLayout(pnlDatosProyLayout);
        pnlDatosProyLayout.setHorizontalGroup(
            pnlDatosProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosProyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosProyLayout.createSequentialGroup()
                        .addGroup(pnlDatosProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUbica)
                            .addComponent(lblTec))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDatosProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosProyLayout.createSequentialGroup()
                                .addGroup(pnlDatosProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtUbica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(txtTec, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDatosProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCity)
                                    .addComponent(lblTab))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDatosProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTab)
                                    .addComponent(txtCity)))
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlDatosProyLayout.createSequentialGroup()
                        .addComponent(lblTitRuta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRutaCSV)))
                .addContainerGap())
        );
        pnlDatosProyLayout.setVerticalGroup(
            pnlDatosProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosProyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDatosProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUbica)
                    .addComponent(txtUbica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTec)
                    .addComponent(txtTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRutaCSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitRuta)))
        );

        pnlDatoME435.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.pnlDatoME435.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION)); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblBobina, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.lblBobina.text")); // NOI18N

        cmbRelBob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "600", "1000", "3000", "6000" }));
        cmbRelBob.setToolTipText(org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.cmbRelBob.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblRelTension, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.lblRelTension.text")); // NOI18N
        lblRelTension.setToolTipText(org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.lblRelTension.toolTipText")); // NOI18N

        txtRelPrim.setText(org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.txtRelPrim.text")); // NOI18N
        txtRelPrim.setToolTipText(org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.txtRelPrim.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblA, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.lblA.text")); // NOI18N

        txtRelPrim1.setText(org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.txtRelPrim1.text")); // NOI18N
        txtRelPrim1.setToolTipText(org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.txtRelPrim1.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblPeriod, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.lblPeriod.text")); // NOI18N

        spnPeriod.setToolTipText(org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.spnPeriod.toolTipText")); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/gcto/dataVDM/ME435.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.jLabel1.text")); // NOI18N

        btnCrear.setBackground(new java.awt.Color(153, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(btnCrear, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.btnCrear.text")); // NOI18N
        btnCrear.setToolTipText(org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.btnCrear.toolTipText")); // NOI18N

        javax.swing.GroupLayout pnlDatoME435Layout = new javax.swing.GroupLayout(pnlDatoME435);
        pnlDatoME435.setLayout(pnlDatoME435Layout);
        pnlDatoME435Layout.setHorizontalGroup(
            pnlDatoME435Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatoME435Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatoME435Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlDatoME435Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlDatoME435Layout.createSequentialGroup()
                            .addComponent(lblBobina)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmbRelBob, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlDatoME435Layout.createSequentialGroup()
                            .addComponent(lblRelTension)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtRelPrim, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblA)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtRelPrim1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlDatoME435Layout.createSequentialGroup()
                        .addComponent(lblPeriod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spnPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnCrear)
                .addContainerGap())
        );
        pnlDatoME435Layout.setVerticalGroup(
            pnlDatoME435Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatoME435Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatoME435Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatoME435Layout.createSequentialGroup()
                        .addGroup(pnlDatoME435Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBobina)
                            .addComponent(cmbRelBob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatoME435Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRelTension)
                            .addGroup(pnlDatoME435Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtRelPrim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblA)
                                .addComponent(txtRelPrim1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatoME435Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPeriod)))
                    .addGroup(pnlDatoME435Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnCrear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlProyLayout = new javax.swing.GroupLayout(pnlProy);
        pnlProy.setLayout(pnlProyLayout);
        pnlProyLayout.setHorizontalGroup(
            pnlProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlDatoME435, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pnlDatosProy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlProyLayout.setVerticalGroup(
            pnlProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDatosProy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDatoME435, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCrearProyLayout = new javax.swing.GroupLayout(pnlCrearProy);
        pnlCrearProy.setLayout(pnlCrearProyLayout);
        pnlCrearProyLayout.setHorizontalGroup(
            pnlCrearProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrearProyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCrearProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlProy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlCrearProyLayout.createSequentialGroup()
                        .addGroup(pnlCrearProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(flieChoosserCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitCSV))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlCrearProyLayout.setVerticalGroup(
            pnlCrearProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrearProyLayout.createSequentialGroup()
                .addComponent(lblTitCSV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flieChoosserCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlProy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlProy.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.pnlProy.AccessibleContext.accessibleName")); // NOI18N
        pnlProy.getAccessibleContext().setAccessibleDescription(org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.pnlProy.AccessibleContext.accessibleDescription")); // NOI18N

        tabbPnl.addTab(org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.pnlCrearProy.TabConstraints.tabTitle"), pnlCrearProy); // NOI18N

        lblTitVMD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lblTitVMD, org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.lblTitVMD.text")); // NOI18N

        javax.swing.GroupLayout pnlAbrirProyLayout = new javax.swing.GroupLayout(pnlAbrirProy);
        pnlAbrirProy.setLayout(pnlAbrirProyLayout);
        pnlAbrirProyLayout.setHorizontalGroup(
            pnlAbrirProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAbrirProyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAbrirProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileCooserVMD, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblTitVMD, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlAbrirProyLayout.setVerticalGroup(
            pnlAbrirProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAbrirProyLayout.createSequentialGroup()
                .addComponent(lblTitVMD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileCooserVMD, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbPnl.addTab(org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.pnlAbrirProy.TabConstraints.tabTitle"), pnlAbrirProy); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tabbPnl)
                    .addComponent(lblTit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbPnl)
                .addContainerGap())
        );

        tabbPnl.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.Abrir.AccessibleContext.accessibleName")); // NOI18N
        tabbPnl.getAccessibleContext().setAccessibleDescription(org.openide.util.NbBundle.getMessage(AbrirProyectoNuevo.class, "AbrirProyectoNuevo.Abrir.AccessibleContext.accessibleDescription")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb3ph3wActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rb3ph3wActionPerformed
    {//GEN-HEADEREND:event_rb3ph3wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb3ph3wActionPerformed

    private void rb3ph3wLLNActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rb3ph3wLLNActionPerformed
    {//GEN-HEADEREND:event_rb3ph3wLLNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb3ph3wLLNActionPerformed

    private void rb3ph4wActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rb3ph4wActionPerformed
    {//GEN-HEADEREND:event_rb3ph4wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb3ph4wActionPerformed

    private void rb3ph2wLNActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rb3ph2wLNActionPerformed
    {//GEN-HEADEREND:event_rb3ph2wLNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb3ph2wLNActionPerformed

    private void rb1ph2wLLActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rb1ph2wLLActionPerformed
    {//GEN-HEADEREND:event_rb1ph2wLLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1ph2wLLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                AbrirProyectoNuevo dialog = new AbrirProyectoNuevo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.ButtonGroup btnGrp;
    private javax.swing.JComboBox<String> cmbRelBob;
    private javax.swing.JFileChooser fileCooserVMD;
    private javax.swing.JFileChooser flieChoosserCSV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl1ph2wll;
    private javax.swing.JLabel lbl1ph2wln;
    private javax.swing.JLabel lbl1ph3wlln;
    private javax.swing.JLabel lbl3ph3w;
    private javax.swing.JLabel lbl3ph3wlN;
    private javax.swing.JLabel lbl3ph3wlln;
    private javax.swing.JLabel lbl3ph4w;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblBobina;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPeriod;
    private javax.swing.JLabel lblRelTension;
    private javax.swing.JLabel lblTab;
    private javax.swing.JLabel lblTec;
    private javax.swing.JLabel lblTit;
    private javax.swing.JLabel lblTitCSV;
    private javax.swing.JLabel lblTitRuta;
    private javax.swing.JLabel lblTitVMD;
    private javax.swing.JLabel lblUbica;
    private javax.swing.JPanel pnlAbrirProy;
    private javax.swing.JPanel pnlCrearProy;
    private javax.swing.JPanel pnlDatoME435;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlDatosProy;
    private javax.swing.JPanel pnlProy;
    private javax.swing.JRadioButton rb1ph2wLL;
    private javax.swing.JRadioButton rb1ph2wLN;
    private javax.swing.JRadioButton rb1ph3wLLN;
    private javax.swing.JRadioButton rb3ph2wLN;
    private javax.swing.JRadioButton rb3ph3w;
    private javax.swing.JRadioButton rb3ph3wLLN;
    private javax.swing.JRadioButton rb3ph4w;
    private javax.swing.JSpinner spnPeriod;
    private javax.swing.JTabbedPane tabbPnl;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRelPrim;
    private javax.swing.JTextField txtRelPrim1;
    private javax.swing.JTextField txtRutaCSV;
    private javax.swing.JTextField txtTab;
    private javax.swing.JTextField txtTec;
    private javax.swing.JTextField txtUbica;
    // End of variables declaration//GEN-END:variables
}
