/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.gcto.dataInformes;

import com.openhtmltopdf.pdfboxout.PdfRendererBuilder;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Base64;
import java.util.Set;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.gcto.dataGlobal.baseTopComponent;
import org.gcto.dataGlobal.glb;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;

/**
 * Diálogo para configurar y generar el informe técnico en PDF.
 *
 * @author camilo
 */
public class GenerarInforme extends javax.swing.JDialog
{

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GenerarInforme.class.getName());

    /**
     * Creates new form generarInforme
     */
    public GenerarInforme(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        setIconImage((new ImageIcon(getClass().getResource("informe.png"))).getImage());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(GenerarInforme.class, "generarInforme.title")); // NOI18N
        setIconImage(null);
        setIconImages(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(GenerarInforme.class, "GenerarInforme.jLabel1.text")); // NOI18N
        jLabel1.setOpaque(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnCancel, org.openide.util.NbBundle.getMessage(GenerarInforme.class, "GenerarInforme.btnCancel.text")); // NOI18N
        btnCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelActionPerformed(evt);
            }
        });

        btnAceptar.setBackground(new java.awt.Color(204, 255, 204));
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnAceptar, org.openide.util.NbBundle.getMessage(GenerarInforme.class, "GenerarInforme.btnAceptar.text")); // NOI18N
        btnAceptar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAceptar.setOpaque(true);
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAceptar, btnCancel});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAceptar, btnCancel});

        jScrollPane2.setHorizontalScrollBar(null);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(org.openide.util.NbBundle.getMessage(GenerarInforme.class, "GenerarInforme.jTextArea1.text")); // NOI18N
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setAutoscrolls(false);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, 32767))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_btnAceptarActionPerformed
        generateReport();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void generateReport()
    {
        File targetFile;
        if (glb.seletedFileVDM != null)
        {
            String parent = glb.seletedFileVDM.getParent();
            String name = glb.dp.getNombreProy() != null ? glb.dp.getNombreProy().replaceAll("[^a-zA-Z0-9.-]", "_") : "SinNombre";
            targetFile = new File(parent, "Informe_" + name + ".pdf");
        } else
        {
            JFileChooser fc = new JFileChooser();
            fc.setDialogTitle("Guardar Informe PDF");
            fc.setFileFilter(new FileNameExtensionFilter("Documento PDF (*.pdf)", "pdf"));
            if (fc.showSaveDialog(this) != JFileChooser.APPROVE_OPTION)
            {
                return;
            }
            targetFile = fc.getSelectedFile();
            if (!targetFile.getName().toLowerCase().endsWith(".pdf"))
            {
                targetFile = new File(targetFile.getAbsolutePath() + ".pdf");
            }
        }

        try (OutputStream os = new FileOutputStream(targetFile))
        {
            PdfRendererBuilder builder = new PdfRendererBuilder();
            builder.useFastMode();
            builder.withHtmlContent(getHtmlContent(), null);
            builder.toStream(os);
            builder.run();

            JOptionPane.showMessageDialog(this, "Informe generado con éxito en:\n" + targetFile.getAbsolutePath());
            dispose();
        } catch (Exception e)
        {
            logger.log(java.util.logging.Level.SEVERE, "Error al generar el informe", e);
            JOptionPane.showMessageDialog(this, "Error al generar el informe: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private String getHtmlContent()
    {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        String fecha = LocalDateTime.now().format(dtf);

        StringBuilder html = new StringBuilder();
        html.append("<!DOCTYPE html><html><head><style>");
        html.append("body { font-family: 'Arial', sans-serif; margin: 5px 20px 20px 20px; color: #333; }");
        html.append(".header { border-bottom: 1px solid #003333; padding-bottom: 2px; margin-bottom: 2px; }");
        html.append(".title { font-size: 16pt; font-weight: bold; color: #003333; text-align: center; }"); 
        html.append(".date { text-align: right; font-size: 10pt; margin-bottom: 10px; }");
        html.append(".section { margin-top: 5px; }");
        html.append(".section-title { font-weight: bold; background-color: #e6f2f2; padding: 2px 8px; border-left: 4px solid #003333; margin-bottom: 4px; font-size: 12pt; }");
        html.append("table { width: 100%; border-collapse: collapse; margin-bottom: 5px; }");
        html.append("td, th { padding: 0px 2px; vertical-align: top; font-size: 8pt; border: 1px solid #eee; }"); 
        html.append("th { background-color: #f2f2f2; font-weight: bold; text-align: left; }");
        html.append(".label { font-weight: bold; width: 35%; color: #555; border: none; }");
        html.append(".comment-box { padding: 8px; border: 1px solid #ccc; background-color: #fafafa; min-height: 40px; font-style: italic; font-size: 10pt; }");
        html.append(".chart-img { width: 100%; border: 1px solid #ddd; margin-bottom: 5px; }");
        html.append(".page-break { page-break-before: always; }");
        
        // Estilos para el pie de página con numeración y línea divisoria
        html.append("@page { size: letter; margin: 1.5cm; @bottom-right { content: element(footer); } }");
        html.append("#footer { position: running(footer); width: 100%; border-top: 1px solid #003333; text-align: right; padding-top: 3px; font-size: 8pt; }");
        html.append(".page-number:after { content: \"Hoja \" counter(page) \" de \" counter(pages); }");
        
        html.append("</style></head><body>");

        // Definición del pie de página que se repetirá en todas las hojas
        html.append("<div id='footer'><span class='page-number'></span></div>");

        String logoPath = glb.opc.getLogoPath();
        String logoHtml = "";
        if (logoPath != null && !logoPath.isEmpty() && !logoPath.equals("ENTRE LA RUTA DEL LOGO"))
        {
            File f = new File(logoPath);
            if (f.exists())
            {
                logoHtml = "<div style='text-align: left;'><img src='" + f.toURI().toString() + "' style='width: 180px; height: 100px;' /></div>";
            }
        }

        // --- HOJA 1: DATOS GENERALES ---
        html.append("<div class='header'>");
        html.append(logoHtml);
        String proyName = glb.dp.getNombreProy() != null ? glb.dp.getNombreProy() : "";
        html.append("<div class='title'>INFORME MEDICIÓN MEATROL ME 435").append(proyName.isEmpty() ? "" : " - " + proyName).append("</div></div>");
        
        html.append("<div class='date'>Fecha de creación: ").append(fecha).append("</div>");

        // DATOS DEL CLIENTE
        html.append("<div class='section'><div class='section-title'>DATOS DEL CLIENTE</div>");
        html.append("<table style='border: none;'>");
        html.append("<tr><td class='label' style='font-size:12pt;'>Nombre Proyecto:</td><td style='border:none; font-size:12pt;'>").append(proyName).append("</td></tr>");
        html.append("<tr><td class='label' style='font-size:12t;'>Ciudad:</td><td style='border:none; font-size:12pt;'>").append(glb.dp.getCiudadProy() != null ? glb.dp.getCiudadProy() : "").append("</td></tr>");
        html.append("<tr><td class='label' style='font-size:12pt;'>Ubicación:</td><td style='border:none; font-size:12pt;'>").append(glb.dp.getUbicacionProy() != null ? glb.dp.getUbicacionProy() : "").append("</td></tr>");
        html.append("</table></div>");

        // OPERADOR
        html.append("<div class='section'><div class='section-title'>OPERADOR</div>");
        html.append("<table style='border: none;'>");
        html.append("<tr><td class='label' style='font-size:12pt;'>Operador ME:</td><td style='border:none; font-size:12pt;'>").append(glb.dp.getOperadorME() != null ? glb.dp.getOperadorME() : "").append("</td></tr>");
        html.append("</table></div>");

        // DATOS DE EQUIPO
        html.append("<div class='section'><div class='section-title'>DATOS DE EQUIPO</div>");
        html.append("<table style='border: none;'>");
        html.append("<tr><td class='label' style='font-size:12pt;'>Relación Bobina:</td><td style='border:none; font-size:12pt;'>").append(glb.dp.getRelacionBobina()).append("</td></tr>");
        html.append("<tr><td class='label' style='font-size:12pt;'>Relación Tensión Primaria:</td><td style='border:none; font-size:12pt;'>").append(glb.dp.getRelacionTensionPrim()).append("</td></tr>");
        html.append("<tr><td class='label' style='font-size:12pt;'>Relación Tensión Secundaria:</td><td style='border:none; font-size:12pt;'>").append(glb.dp.getRelacionTensionSec()).append("</td></tr>");
        html.append("<tr><td class='label' style='font-size:12pt;'>Periodo SD (s):</td><td style='border:none; font-size:12pt;'>").append(glb.dp.getPeriodoSD()).append("</td></tr>");
        html.append("</table></div>");

        // DATOS INSTALACION
        html.append("<div class='section'><div class='section-title'>DATOS INSTALACIÓN</div>");
        html.append("<table style='border: none;'>");
        html.append("<tr><td class='label' style='font-size:12pt;'>Tablero:</td><td style='border:none; font-size:12pt;'>").append(glb.dp.getTablero() != null ? glb.dp.getTablero() : "").append("</td></tr>");
        html.append("<tr><td class='label' style='font-size:12pt;'>Tipo de Red:</td><td style='border:none; font-size:12pt;'>").append(glb.dp.getTipoRed() != null ? glb.dp.getTipoRed() : "").append("</td></tr>");
        html.append("</table></div>");

        // COMENTARIO
        html.append("<div class='section'><div class='section-title'>COMENTARIO</div>");
        html.append("<div class='comment-box'>").append(glb.dp.getComentario() != null ? glb.dp.getComentario() : "").append("</div></div>");

        // --- HOJAS ADICIONALES: FORMULARIOS ABIERTOS ---
        Set<TopComponent> opened = WindowManager.getDefault().getRegistry().getOpened();
        for (TopComponent tc : opened)
        {
            if (tc instanceof baseTopComponent)
            {
                baseTopComponent btc = (baseTopComponent) tc;
                html.append("<div class='page-break'>");
                
                // Título de la hoja (Nombre del formulario / Pestaña)
                String title = btc.getDisplayName();
                if (title == null) title = btc.getName();
                
                // Limpieza agresiva de "null -" y HTML
                if (title != null) {
                    title = title.replaceAll("<[^>]*>", ""); // Quitar HTML
                    // Quitar "null" o "null -" al inicio (insensible a mayúsculas)
                    title = title.replaceFirst("(?i)^null\\s*[-–—:]*\\s*", "");
                    title = title.trim();
                }
                
                if (title == null || title.isEmpty() || title.equalsIgnoreCase("null")) {
                    title = "Análisis de Datos";
                }
                
                html.append("<div class='header'><div class='title'>").append(title).append("</div></div>");
                
                // Captura del gráfico (Fondo blanco forzado)
                BufferedImage chartImg = btc.getChartPanel().getSnapshotImage(1400, 900);
                String base64Chart = imageToBase64(chartImg);
                html.append("<div class='section'><img class='chart-img' src='").append(base64Chart).append("' /></div>");
                
                // Tabla de estadísticas estandarizada a 7 columnas
                html.append("<div class='section'><div class='section-title'>ESTADÍSTICAS</div>");
                html.append("<table><thead><tr>");
                html.append("<th>Color</th>");
                html.append("<th>Nombre</th>");
                html.append("<th>Mínimo</th>");
                html.append("<th>Fecha del Mínimo</th>");
                html.append("<th>Promedio</th>");
                html.append("<th>Máximo</th>");
                html.append("<th>Fecha del Máximo</th>");
                html.append("</tr></thead><tbody>");
                
                DefaultTableModel model = btc.getStatsModel();
                // Mapeo exacto: Nombre(1), Min(3), Fecha Min(4), Prom(5), Max(7), Fecha Max(8)
                int[] dataCols = {1, 3, 4, 5, 7, 8}; 
                
                for (int row = 0; row < model.getRowCount(); row++) {
                    // Solo incluimos filas que el usuario tiene marcadas como visibles (columna 2)
                    if (!(boolean) model.getValueAt(row, 2)) continue;
                    
                    html.append("<tr>");
                    
                    // Columna Color: Renderizado como caja de color con borde para contraste
                    Color c = (Color) model.getValueAt(row, 0);
                    String hexColor = String.format("#%02x%02x%02x", c.getRed(), c.getGreen(), c.getBlue());
                    html.append("<td style='text-align: center;'><div style='width: 14px; height: 9px; background-color: ").append(hexColor).append("; margin: auto; border: 1px solid #999;'></div></td>");
                    
                    for (int colIdx : dataCols) {
                        Object val = model.getValueAt(row, colIdx);
                        html.append("<td>").append(val != null ? val.toString() : "").append("</td>");
                    }
                    html.append("</tr>");
                }
                html.append("</tbody></table></div>");
                
                html.append("</div>"); // Fin de página
            }
        }

        html.append("</body></html>");
        return html.toString();
    }

    private String imageToBase64(BufferedImage img)
    {
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream())
        {
            ImageIO.write(img, "png", baos);
            byte[] bytes = baos.toByteArray();
            return "data:image/png;base64," + Base64.getEncoder().encodeToString(bytes);
        } catch (Exception e)
        {
            logger.log(java.util.logging.Level.WARNING, "Error convirtiendo imagen a Base64", e);
            return "";
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                GenerarInforme dialog = new GenerarInforme(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
