/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.gcto.dataInformes;

import com.openhtmltopdf.pdfboxout.PdfRendererBuilder;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.gcto.dataGlobal.glb;




/**
 * Diálogo para configurar y generar el informe técnico en PDF.
 *
 * @author camilo
 */
public class GenerarInforme extends javax.swing.JDialog
{

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GenerarInforme.class.getName());

    /**
     * Creates new form generarInforme
     */
    public GenerarInforme(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        setIconImage((new ImageIcon(getClass().getResource("informe.png"))).getImage());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(GenerarInforme.class, "generarInforme.title")); // NOI18N
        setIconImage(null);
        setIconImages(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(GenerarInforme.class, "GenerarInforme.jLabel1.text")); // NOI18N
        jLabel1.setOpaque(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnCancel, org.openide.util.NbBundle.getMessage(GenerarInforme.class, "GenerarInforme.btnCancel.text")); // NOI18N
        btnCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelActionPerformed(evt);
            }
        });

        btnAceptar.setBackground(new java.awt.Color(204, 255, 204));
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnAceptar, org.openide.util.NbBundle.getMessage(GenerarInforme.class, "GenerarInforme.btnAceptar.text")); // NOI18N
        btnAceptar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAceptar.setOpaque(true);
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAceptar, btnCancel});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAceptar, btnCancel});

        jScrollPane2.setHorizontalScrollBar(null);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(org.openide.util.NbBundle.getMessage(GenerarInforme.class, "GenerarInforme.jTextArea1.text")); // NOI18N
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setAutoscrolls(false);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_btnAceptarActionPerformed
        generateReport();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void generateReport()
    {
        File targetFile;
        if (glb.seletedFileVDM != null)
        {
            String parent = glb.seletedFileVDM.getParent();
            String name = glb.dp.getNombreProy().replaceAll("[^a-zA-Z0-9.-]", "_");
            targetFile = new File(parent, "Informe_" + name + ".pdf");
        } else
        {
            JFileChooser fc = new JFileChooser();
            fc.setDialogTitle("Guardar Informe PDF");
            fc.setFileFilter(new FileNameExtensionFilter("Documento PDF (*.pdf)", "pdf"));
            if (fc.showSaveDialog(this) != JFileChooser.APPROVE_OPTION)
            {
                return;
            }
            targetFile = fc.getSelectedFile();
            if (!targetFile.getName().toLowerCase().endsWith(".pdf"))
            {
                targetFile = new File(targetFile.getAbsolutePath() + ".pdf");
            }
        }

        try (OutputStream os = new FileOutputStream(targetFile))
        {
            PdfRendererBuilder builder = new PdfRendererBuilder();
            builder.useFastMode();
            builder.withHtmlContent(getHtmlContent(), null);
            builder.toStream(os);
            builder.run();

            JOptionPane.showMessageDialog(this, "Informe generado con éxito en:\n" + targetFile.getAbsolutePath());
            dispose();
        } catch (Exception e)
        {
            logger.log(java.util.logging.Level.SEVERE, "Error al generar el informe", e);
            JOptionPane.showMessageDialog(this, "Error al generar el informe: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private String getHtmlContent()
    {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        String fecha = LocalDateTime.now().format(dtf);

        StringBuilder html = new StringBuilder();
        html.append("<!DOCTYPE html><html><head><style>");
        html.append("body { font-family: 'Arial', sans-serif; margin: 10px 40px 40px 40px; color: #333; }");
        html.append(".header { border-bottom: 2px solid #003333; padding-bottom: 10px; margin-bottom: 5px; }");
        html.append(".title { font-size: 22pt; font-weight: bold; color: #003333; text-align: center; }");
        html.append(".date { text-align: right; font-size: 10pt; margin-bottom: 20px; }");
        html.append(".section { margin-top: 15px; }");
        html.append(".section-title { font-weight: bold; background-color: #e6f2f2; padding: 5px 10px; border-left: 5px solid #003333; margin-bottom: 8px; font-size: 12pt; }");
        html.append("table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }");
        html.append("td { padding: 4px 8px; vertical-align: top; font-size: 11pt; }");
        html.append(".label { font-weight: bold; width: 35%; color: #555; }");
        html.append(".comment-box { padding: 10px; border: 1px solid #ccc; background-color: #fafafa; min-height: 50px; font-style: italic; }");
        html.append("</style></head><body>");

        String logoPath = glb.opc.getLogoPath();
        String logoHtml = "";
        if (logoPath != null && !logoPath.isEmpty() && !logoPath.equals("ENTRE LA RUTA DEL LOGO"))
        {
            File f = new File(logoPath);
            if (f.exists())
            {
                logoHtml = "<div style='text-align: left;'><img src='" + f.toURI().toString() + "' style='width: 210px; height: 120px;' /></div>";
            }
        }

        html.append("<div class='header'>");
        html.append(logoHtml);
        html.append("<div class='title'>INFORME MEDICIÓN MEATROL ME 435</div></div>");
        
        html.append("<div class='date'>Fecha de creación: ").append(fecha).append("</div>");

        // DATOS DEL CLIENTE
        html.append("<div class='section'><div class='section-title'>DATOS DEL CLIENTE</div>");
        html.append("<table>");
        html.append("<tr><td class='label'>Nombre Proyecto:</td><td>").append(glb.dp.getNombreProy()).append("</td></tr>");
        html.append("<tr><td class='label'>Ciudad:</td><td>").append(glb.dp.getCiudadProy()).append("</td></tr>");
        html.append("<tr><td class='label'>Ubicación:</td><td>").append(glb.dp.getUbicacionProy()).append("</td></tr>");
        html.append("</table></div>");

        // OPERADOR
        html.append("<div class='section'><div class='section-title'>OPERADOR</div>");
        html.append("<table>");
        html.append("<tr><td class='label'>Operador ME:</td><td>").append(glb.dp.getOperadorME()).append("</td></tr>");
        html.append("</table></div>");

        // DATOS DE EQUIPO
        html.append("<div class='section'><div class='section-title'>DATOS DE EQUIPO</div>");
        html.append("<table>");
        html.append("<tr><td class='label'>Relación Bobina:</td><td>").append(glb.dp.getRelacionBobina()).append("</td></tr>");
        html.append("<tr><td class='label'>Relación Tensión Primaria:</td><td>").append(glb.dp.getRelacionTensionPrim()).append("</td></tr>");
        html.append("<tr><td class='label'>Relación Tensión Secundaria:</td><td>").append(glb.dp.getRelacionTensionSec()).append("</td></tr>");
        html.append("<tr><td class='label'>Periodo SD (s):</td><td>").append(glb.dp.getPeriodoSD()).append("</td></tr>");
        html.append("</table></div>");

        // DATOS INSTALACION
        html.append("<div class='section'><div class='section-title'>DATOS INSTALACIÓN</div>");
        html.append("<table>");
        html.append("<tr><td class='label'>Tablero:</td><td>").append(glb.dp.getTablero()).append("</td></tr>");
        html.append("<tr><td class='label'>Tipo de Red:</td><td>").append(glb.dp.getTipoRed()).append("</td></tr>");
        html.append("</table></div>");

        // COMENTARIO
        html.append("<div class='section'><div class='section-title'>COMENTARIO</div>");
        html.append("<div class='comment-box'>").append(glb.dp.getComentario()).append("</div></div>");

        html.append("</body></html>");
        return html.toString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                GenerarInforme dialog = new GenerarInforme(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
